<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <FlyAppName>webfrontend</FlyAppName>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AlefCarlos.AspNetCoreDefaults" />
  </ItemGroup>

</Project>
