<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Flyio.Demo.GraphQLService.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Flyio.Demo.GraphQLService\Flyio.Demo.GraphQLService.csproj" />
  </ItemGroup>
</Project>
