<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- Analyzers/Builds -->
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15" />
    <GlobalPackageReference Include="MinVer" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="AlefCarlos.AspNetCore.WebApi" Version="1.0.2" />
    <PackageVersion Include="AlefCarlos.AspNetCoreDefaults" Version="1.0.2" />
    <PackageVersion Include="Steeltoe.Configuration.ConfigServer" Version="4.1.0" />
    <PackageVersion Include="Steeltoe.Configuration.Placeholder" Version="4.1.0" />
  </ItemGroup>
  <!-- Aspire -->
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.Keycloak" Version="13.2.3-preview.1.26217.6" />
  </ItemGroup>
</Project>