<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <FlyAppName>apiservice</FlyAppName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AlefCarlos.AspNetCore.WebApi" />
  </ItemGroup>
</Project>
