<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<FlyAppName>apiservice</FlyAppName>
	  <UserSecretsId>13e6dfb7-860b-4703-ab0f-ae7e75fcfbb5</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AlefCarlos.AspNetCore.WebApi" />
		<PackageReference Include="Ardalis.Result.FluentValidation" />
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Mediator.SourceGenerator">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>
</Project>
