<Project Sdk="Aspire.AppHost.Sdk/13.2.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>118ee23f-c5d9-4935-96c9-4991c066cb88</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flyio.Demo.ApiService\Flyio.Demo.ApiService.csproj" />
    <ProjectReference Include="..\Flyio.Demo.Web\Flyio.Demo.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Keycloak" />
  </ItemGroup>

</Project>
