<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Flyio.Demo.ApiService.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Flyio.Demo.SharedKernel\Flyio.Demo.SharedKernel.csproj" />
    </ItemGroup>
</Project>
