<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsModule>true</IsModule>
    <ModuleName>Todos</ModuleName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Flyio.Demo.ApiService.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flyio.Demo.Todos.Contracts\Flyio.Demo.Todos.Contracts.csproj" />
  </ItemGroup>
</Project>
