<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Build.props, $(MSBuildThisFileDirectory)..))" />

  <ItemGroup Condition="'$(ModuleName)' != ''">
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ModuleName</_Parameter1>
      <_Parameter2>$(ModuleName)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup Condition="'$(IsModule)' == 'true'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <InternalsVisibleTo Include="Flyio.Demo.ApiService" />
    <InternalsVisibleTo Include="Flyio.Demo.GraphQLService" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsModule)' == 'true'">
    <PackageReference Include="AlefCarlos.AspNetCore.WebApi" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsModule)' == 'true'">
    <ProjectReference Include="..\Flyio.Demo.Module.SharedKernel\Flyio.Demo.Module.SharedKernel.csproj" />
  </ItemGroup>
</Project>